src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"mail"}, message="L'email est déjà utilisé")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=120)
     * @Assert\Email(
     *     message = "Merci de rentrer une adresse mail valide"
     * )
     */
    private $mail;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex(
     *      pattern="/^[a-zA-Z-éèàäçï]+$['-]?/",
     *      match=true,
     *      message="Votre nom ne doit contenir que des caractères entre A et Z")
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex(
     *      pattern="/^[a-zA-Z-éèàäçï]+$['-]?/",
     *      match=true,
     *      message="Votre prénom ne doit contenir que des caractères entre A et Z")
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=20)
     * @Assert\Regex(pattern="/(0|\+33)[1-9]( *[0-9]{2}){4}/",
     *               htmlPattern = "^(0|\+33)[1-9]( *[0-9]{2}){4}+$",
     *                 message="Veuillez rentrer un numéro de téléphone valide")
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $code_post;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $commune;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="8", minMessage="Votre mot de Passe doit faire au moins 8 caractères")
     */
    private $password;

    /**
     * @Assert\EqualTo(propertyPath="password", message="Erreur, merci de confirmer votre mot de passe")
     */
    public $confirm_password;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Annonces", mappedBy="id_posteur", orphanRemoval=true)
     */
    private $annonces;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $roles = [];

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $departement;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $activation_token;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $reset_token;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="emetteur", orphanRemoval=true)
     */
    private $messages;

    public function __construct()
    {
        $this->annonces = new ArrayCollection();
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = htmlspecialchars($mail);

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = htmlspecialchars($nom);

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = htmlspecialchars($prenom);

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = htmlspecialchars($telephone);

        return $this;
    }

    public function getCodePost(): ?string
    {
        return $this->code_post;
    }

    public function setCodePost(string $code_post): self
    {
        $this->code_post = htmlspecialchars($code_post);

        return $this;
    }

    public function getCommune(): ?string
    {
        return $this->commune;
    }

    public function setCommune(string $commune): self
    {
        $this->commune = htmlspecialchars($commune);

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function eraseCredentials(){}

    public function getSalt(){}

    public function getRoles()
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }
    public function getUserName()
    {
        return $this->mail;
    }

    /**
     * @return Collection|Annonces[]
     */
    public function getAnnonces(): Collection
    {
        return $this->annonces;
    }

    public function addAnnonce(Annonces $annonce): self
    {
        if (!$this->annonces->contains($annonce)) {
            $this->annonces[] = $annonce;
            $annonce->setIdPosteur($this);
        }

        return $this;
    }

    public function removeAnnonce(Annonces $annonce): self
    {
        if ($this->annonces->contains($annonce)) {
            $this->annonces->removeElement($annonce);
            // set the owning side to null (unless already changed)
            if ($annonce->getIdPosteur() === $this) {
                $annonce->setIdPosteur(null);
            }
        }

        return $this;
    }

    public function setRoles(?array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getDepartement(): ?string
    {
        return $this->departement;
    }

    public function setDepartement(string $departement): self
    {
        $this->departement = $departement;

        return $this;
    }

    public function getActivationToken(): ?string
    {
        return $this->activation_token;
    }

    public function setActivationToken(?string $activation_token): self
    {
        $this->activation_token = $activation_token;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->reset_token;
    }

    public function setResetToken(?string $reset_token): self
    {
        $this->reset_token = $reset_token;

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setEmetteur($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getEmetteur() === $this) {
                $message->setEmetteur(null);
            }
        }

        return $this;
    }
}

src/Controller/SiteController.php
<?php

namespace App\Controller;

use App\Entity\Annonces;
use App\Entity\User;
use App\Repository\AnnoncesRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class SiteController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index()
    {
        return $this->render('site/index.html.twig', [
        'controller_name' => 'SiteController',
        ]);
    }
    /**
     * @Route("/user/{id}/profil", name ="profile")
     */
    public function profil($id, UserRepository $repoUse, AnnoncesRepository $repoann)
    {
        $annonces = $repoann->findBy(["id_posteur" => $id]);
        $user = $repoUse->find($id);
        return $this->render('site/profil.html.twig', [
            'user' => $user,
            'annonces' => $annonces
        ]);
    }
    /**
     * @Route("/user/{id}/new", name="new")
     */
    public function addAnnonce($id, Request $request, EntityManagerInterface $manager, UserRepository $repo)
    {
        $user = $repo->find($id);
        $annonce = new Annonces;
        $annonce->setIdPosteur($user);
        $annonce->setValide(0);
        $form = $this->createFormBuilder($annonce)
            ->add('titre', TextType::class)
            ->add('contenu', TextareaType::class)
            ->add('type', ChoiceType::class, [
                'choices' => [
                    'Recherche' => 'recherche',
                    'Proposition' => 'proposition'
                ]
            ])
            ->add('contrepartie', TextareaType::class)
            ->getForm();
        
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid() ){
            $manager->persist($annonce);
            $manager->flush();

            $this->addFlash(
                'notice',
                'Votre annonce a bien été enregistrée ! Elle sera mise en ligne après vérification par un modérateur'
            );
            return $this->redirectToRoute('profile', ['id'=> $id]);
        }

        return $this->render('site/formAnnonce.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/annonce/{id}", name="annonce")
     */
    public function showAnnonce($id, AnnoncesRepository $repo)
    {
        return $this->render('site/annonce.html.twig', [
            'annonce' => $repo->find($id),
            'posteur' => $repo->find($id)->getIdPosteur()
        ]);
    }
    
    /**
     * @Route("/annonce/{id}/update", name="update")
     */
    public function updateAnnonce($id, Request $request, EntityManagerInterface $manager, AnnoncesRepository $repo)
    {
        $annonce = $repo->find($id);
        $user = $annonce->getIdPosteur()->getId();

        if (!$annonce OR ($user != $this->getUser()->getId() && !in_array("ROLE_ADMIN", $this->getUser()->getRoles()))) {
            return $this->redirectToRoute('index');
        }
        else {
            $form = $this->createFormBuilder($annonce)
                ->add('titre', TextType::class)
                ->add('contenu', TextareaType::class)
                ->add('type', ChoiceType::class, [
                    'choices' => [
                        'Recherche' => 'recherche',
                        'Proposition' => 'proposition'
                    ]
                ])
                ->add('contrepartie', TextareaType::class)
                ->getForm();
                $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid() ){
                $annonce->setValide(0);
                $manager->persist($annonce);
                $manager->flush();

                return $this->redirectToRoute('profile', ['id'=> $user]);
            }
        }
        return $this->render('site/formAnnonce.html.twig', [
            'form' => $form->createView()
        ]);
    }
    /**
     * @Route("/annonce/{id}/delete", name="delete")
     */
    public function deleteAnnonce($id, EntityManagerInterface $manager, AnnoncesRepository $repo)
    {
        $annonce = $repo->find($id);
        $user = $annonce->getIdPosteur()->getId();

        if (!$annonce OR ($user != $this->getUser()->getId() && !in_array("ROLE_ADMIN", $this->getUser()->getRoles()))) {
            return $this->redirectToRoute('index');
        }
        else {
            $manager->remove($annonce);
            $manager->flush();
            $this->addFlash(
                'notice',
                'Cette annonce à bien été supprimée !'
            );
            if ($user == $this->getUser()->getId()) {
                return $this->redirectToRoute('profile', ['id'=> $user]);
            }
            else{
                return $this->redirectToRoute('allAnnonces');
            }
        }
    }
    /**
     * @Route("/annonces", name="allAnnonces")
     */
    public function allAnnonces(UserRepository $repoUse)
    {   
        $user = $this->getUser()->getCodePost();
        $userscode = $repoUse->findBy(['code_post' => $user]);
        $annonces = [];
        foreach ($userscode as $userexte) {
            $annoncesUser = $userexte->getAnnonces();
            foreach ($annoncesUser as $annonce){
                if ($annonce->getValide() == true) {
                    array_push($annonces, $annonce);
                }
            }
        }
        return $this->render('site/liste_annonces.html.twig', [
            'annonces' => $annonces
        ]);
    }
}

templates/site/annonce.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1 class="text-center">{{annonce.titre}}</h1>

    {% if annonce.valide is same as(false)%}
        <p class="text-center"><span class="badge badge-danger">Cette annonce est en attente de validation par un modérateur</span></p>
    {% elseif annonce.valide is same as(true) and posteur.id is same as(app.user.id) %}
        <p class="text-center"><span class="badge badge-success">Votre annonce est en ligne :)</span></p>
    {% endif %}

    <p class="text-center">{{posteur.codePost}} {{posteur.commune}}</p>
   <p class="text-center">annonce postée par {{posteur.nom}} {{posteur.prenom}}</p>
   <br>
   <h3>Type d'annnonce : {{ annonce.type }}</h3>
   <div class="container">
        <div class="row justify-content-between">
            <div class="col-md-5 annonce">
                {% if annonce.type is same as('recherche') %}
                    <h3 class="text-center">Je cherche de l'aide pour :</h3>
                {% else %}
                    <h3 class="text-center">Je propose comme service:</h3>
                {% endif %}
                <p>{{annonce.contenu}}</p>
            </div>
            <div class="col-md-5 annonce">
                <h3 class="text-center">En échange de :</h3>
                <p>{{annonce.contrepartie}}</p>
            </div>
        </div>
    </div>
    <hr>
    <div class="container">
        <div class="row justify-content-center">
        {% if is_granted('ROLE_ADMIN') or app.user.id is same as(posteur.id) %}
            <a href="{{path('delete',{'id': annonce.id})}}"><button class="btn btn-danger m-1">Supprimer l'annonce</button></a>
            <a href="{{path('update',{'id': annonce.id})}}"><button class="btn btn-warning m-1">Modifier l'annonce</button></a>
        {% endif %}
        {% if is_granted('ROLE_ADMIN') and annonce.valide is same as(false) %}
            <a href="{{path('validate',{'id': annonce.id})}}"><button class="btn btn-success m-1">Valider l'annonce</button></a>
        {% endif %}
        {% if app.user.activationToken is null %}
            <a href="{{path('create_message',{'id': posteur.id})}}"><button class="btn btn-success m-1">Envoyer un message à {{ posteur.prenom }}</button></a>
        {% else %}
            <p>Pour contacter {{posteur.prenom}}, vous devez valider votre compte en cliquant sur le lien qui vous a été envoyé par mail lors de votre inscription</p>
        {% endif %}
        </div>
    </div>
{% endblock %}

templates/site/formAnnonce.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="container mt-5">
        
            {{form_start(form)}}
            <div class="row">
                <div class="col-12 col-md-8">
                    {{form_row(form.titre)}}
                </div>
                <div class="col-12 col-md-4">
                    {{form_row(form.type)}}
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    {{form_row(form.contenu, {'attr': {'class': 'input-message'}})}}
                    {{form_row(form.contrepartie, {'attr': {'class': 'input-message'}})}}
                </div>
            </div>
                <button type="submit" class="btn btn-success">Enregistrer</button>
            {{form_end(form)}}
            

            
        
    </div>

{% endblock %}

templates/site/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Le bon Troc{% endblock %}

{% block body %}

<h1 class="text-center">Le Bon Troc</h1>

<div class="container">
    {% if not app.user %}
    <form action="{{ path('index') }}" method="post">
        <div class="form-group">
            <input placeholder="Adresse email" required name="_username" 
            type="text" class="form-control">
        </div>
        <div class="form-group">
            <input placeholder="Mot de Passe" required name="_password" 
            type="password" class="form-control">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-success">Connexion</button>
            <a href="{{path('forgot_password')}}">Mot de passe oublié ?</a>
        </div>
    </form>
    {% endif %}
    <h1 class="text-center">Qui sommes-nous ?</h1>
    <div class="container">
        <div class="row justify-content-start">
            <div class="col-12 col-lg-6">
                <h3>Un retour à l'humain...</h3>
                <br>
                <img src="https://images.unsplash.com/photo-1461354464878-ad92f492a5a0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"
                class="img-index">
                <p>"Le bon troc" est une initiative ayant pour but de revaloriser les échanges humains, ici vos actions ne seront pas monétaires, vous participerez par du troc ou des services !</p>
            </div>
        </div>
        <div class="row justify-content-end">
            <div class="col-12 col-lg-6">
                <h3>... Pour rassainir nos intéractions</h3>
                <br>
                <img src="https://images.unsplash.com/photo-1579208575657-c595a05383b7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"
                class="img-index">
                <p>Après les récentes crises, Il est plus important que jamais de renouer avec notre communauté proche, sans le prysme économique, nos rapports retrouveront bienveillance et solidarité</p>
            </div>
        </div>
        <div class="row justify-content-start">
            <div class="col-12 col-lg-6">
                <h3>Comment faire ?</h3>
                <br>
                <img src="https://images.unsplash.com/photo-1529007328922-d323f83de273?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"
                class="img-index">
                <p>Pour commencer, inscrivez-vous. Vous pourrez ensuite commencer à rechercher des annonces demandant de l'aide ou proposant un service. Le but de est de se mettre soit
                et ses compétences à dispositions, un geste de votre part est donc demandé en échange d'un service.</p>
            </div>    
        </div>
        <div class="row justify-content-end">
            <div class="col-12 col-lg-6">
                <h3>Quel type de service ?</h3>
                <img src="https://images.unsplash.com/photo-1543747255-94b72995ac74?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80"
                class="img-index">
                <p>Le spectre est très large ! De la vidange de voiture à la préparation de gateaux en passant par le baby-sitting, c'est selon ce que vous avez à offrir.
                Par exemple, une personne peut demander de l'aide pour ramasser des fruits dans son verger en échange d'une partie des fruits récoltés ! </p>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/site/liste_annonces.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonces{% endblock %}

{% block body %}
{% for annonce in annonces %}
    <div class="container mt-2 ">
        <div class="row justify-content bg-light rounded">
            <div class="col p-3">
                <h2>{{ annonce.titre }}</h2>
            </div>
            <div class="col p-3 col mt-auto mb-auto">
            <h3> {{annonce.IdPosteur.codePost}}, {{annonce.IdPosteur.commune}} </h3>
            </div>
            <div class="col p-3 col mt-auto mb-auto">
            <h3>postée par {{annonce.IdPosteur.prenom}}</h3>
            </div>
            <div class="col mt-auto mb-auto">
                <a href="{{path('annonce', {'id': annonce.id})}}">  <button class="btn btn-success">Accéder à l'annonce</button></a>
            </div>
        </div>
    </div>
    </br>
{% endfor %}
{% endblock %}

templates/site/profil.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ user.nom }} {{user.prenom}}{% endblock %}

{% block body %}
            <h1 class="text-center mt-3">{{ user.nom }} {{ user.prenom }}</h1>
<div class="container mt-5">
    <ul class="row">
        <div class="col-12 col-lg-6 text-center">
            <li> {{ user.telephone }} </li>
            <li> {{ user.mail }} </li>
        </div>
        <div class="col-12 col-lg-6 text-center">
            <li> {{user.commune}} </li>
            <li> {{ user.codePost }}, {{ user.departement }} </li>
        </div>
    </ul>
        {% if app.user.id is not same as(user.id) and is_granted('ROLE_ADMIN') %}
        <a href="{{path('create_message', {'id' : user.id})}}"><button class="btn btn-info">Contacter {{user.prenom}}</button></a>
        {% endif %}
    
    {% if app.user.id is same as(user.id) %}
    <a href="{{path('settings', {'id': user.id})}}">Modifier mes informations</a>
    {% endif %}
    <h2>Mes annonces</h2>
    {% if app.user.id is same as(user.id) and app.user.activationToken is null %}
        <div class="d-flex flex-row">
            <a href="{{path('new', {'id': user.id})}}"><button class="btn btn-success m-2">Créer une nouvelle annonce</button></a></br>
            <a href="{{path('mailbox')}}"><button class="btn btn-info m-2">Mes messages</button></a>
        </div>
    {% elseif app.user.id is same as(user.id)  %}
        <p> Pour créer une annonce et envoyer des messages, merci de valider votre compte en cliquant sur le lien qui vous a été envoyé dans votre boîte mail</p>
    {% endif %}

    {% for annonce in annonces %}
    <div class="d-inline-flex flex-wrap bg-light" class="annonces-profil">
        <a href="{{path('annonce', {'id': annonce.id})}}" class="m-4">{{ annonce.titre }}</a>
    </div>
    {% endfor %}
    
    {% if is_granted('ROLE_ADMIN') %}
        <div class="fixed-bottom">
            <a href="{{path('deleteUser', {'id':user.id})}}" onclick="return(confirm('Etes-vous sûr de vouloir supprimer ce compte ?'));"><button class="btn btn-secondary">supprimer le compte</button></a>
        </div>
    {% endif %}
</div>

{% endblock %}